//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MandavAccountingProFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        public int OrgID { get; set; }
        public string OrgName { get; set; }
        public string OrgMailingName { get; set; }
        public string OrgAddress { get; set; }
        public Nullable<int> OrgCountryID { get; set; }
        public Nullable<int> OrgStateID { get; set; }
        public string OrgPincode { get; set; }
        public string OrgPhoneNumber { get; set; }
        public string OrgMobile { get; set; }
        public string OrgFaxNo { get; set; }
        public string OrgEmail { get; set; }
        public string OrgWebsite { get; set; }
        public string Password { get; set; }
        public string OrgPanNo { get; set; }
        public string OrgSaleTaxNo { get; set; }
        public string OrgVatID { get; set; }
        public Nullable<int> CurrencyID { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual State State { get; set; }
    }
}
